FROM node:19-alpine3.15 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY . .

# install node dependencies
RUN echo "npm install in progress..." && npm ci
RUN mkdir dist
CMD ["run", "build" ]

FROM rtsp/lighttpd
COPY --from=build /app/dist /var/www/html

